name: CI/CD Pipeline for URLHub

# This pipeline runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/urlhub-backend:latest

  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest
    # This job will only run if the 'build-and-push' job succeeds
    needs: build-and-push

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            # Navigate to the project directory on the VM
            cd ~/URLHub
            # Pull the latest image from Docker Hub
            sudo docker-compose pull backend
            # Stop the old container and start the new one
            sudo docker-compose up -d --no-deps backend